function [g,h] = SVM_opt_cons_test1(A)
%SVM_OPT_CONS_TEST1
%    [G,H] = SVM_OPT_CONS_TEST1(A)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Jul-2021 02:57:47

t2 = A(1.0);
t3 = A(2.0);
t4 = A(3.0);
t5 = A(4.0);
t6 = A(5.0);
t7 = A(6.0);
t8 = A(7.0);
t9 = A(8.0);
t10 = A(9.0);
t11 = A(1.0e1);
t12 = A(1.1e1);
t13 = A(1.2e1);
t14 = A(1.3e1);
t15 = A(1.4e1);
t16 = A(1.5e1);
t17 = A(1.6e1);
t18 = A(1.7e1);
t19 = A(1.8e1);
t20 = A(1.9e1);
t21 = A(2.0e1);
t22 = A(2.1e1);
t23 = A(2.2e1);
t24 = A(2.3e1);
t25 = A(2.4e1);
t26 = A(2.5e1);
t27 = A(2.6e1);
t28 = A(2.7e1);
t29 = A(2.8e1);
t30 = A(2.9e1);
t31 = A(3.0e1);
t32 = A(3.1e1);
t33 = A(3.2e1);
t34 = A(3.3e1);
t35 = A(3.4e1);
t36 = A(3.5e1);
g = [t2-1.0e2;t3-1.0e2;t4-1.0e2;t5-1.0e2;t6-1.0e2;t7-1.0e2;t8-1.0e2;t9-1.0e2;t10-1.0e2;t11-1.0e2;t12-1.0e2;t13-1.0e2;t14-1.0e2;t15-1.0e2;t16-1.0e2;t17-1.0e2;t18-1.0e2;t19-1.0e2;t20-1.0e2;t21-1.0e2;t22-1.0e2;t23-1.0e2;t24-1.0e2;t25-1.0e2;t26-1.0e2;t27-1.0e2;t28-1.0e2;t29-1.0e2;t30-1.0e2;t31-1.0e2;t32-1.0e2;t33-1.0e2;t34-1.0e2;t35-1.0e2;t36-1.0e2];
if nargout > 1
    h = -t2-t3-t4-t5-t6-t7-t8-t9-t10-t11-t12-t13-t14-t15-t16-t17-t18-t19-t20-t21+t22+t23+t24+t25+t26+t27+t28+t29+t30+t31+t32+t33+t34+t35+t36;
end
